apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "weather-frontend.fullname" . }}-config
  labels:
    {{- include "weather-frontend.labels" . | nindent 4 }}
data:
  REACT_APP_BACKEND_URL: {{ .Values.backendUrl | quote }}
